name: Origins-Pony
version: 1.0.1
main: com.tigerclips1.ponyorigins.OriginsPony
description: A Orgin reborn plugin that add the pony powers from the pony origin datapack aka the mine little pony Unicopia power mod port
api-version: '1.19'
author: TigerClips1

depend:
  - Origins-Reborn
